**NUMPY**

**1.Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.**

In [1]:
import numpy as np

#creating two custom numpy arrays A and B
A = np.arange(5)
B = np.arange(6,11)
print(A)
print(B)

[0 1 2 3 4]
[ 6  7  8  9 10]


In [2]:
#creating a new numpy array by stacking A and B vertically
C = np.vstack([A,B])
C

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [3]:
#creating a new numpy array by stacking A and B horizontally
D = np.hstack([A,B])
D

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10])

**2. Find common elements between A and B. [Hint : Intersection of two sets]**

In [4]:
# finding common elements using intersect1d
np.intersect1d(A,B)

array([], dtype=int32)

**3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]**

In [16]:
#extracting all numbers from A between 1 and 4 

#using np.where to find list of indices where A>1
idx1 = np.where(A >1)
print(idx1)

#using np.where to find list of indices where A<4
idx2 = np.where(A<4)
print(idx2)

#using np.intersect1d to find list of common indices i.e where A is between 1 and 4
idx_common = np.intersect1d(idx1,idx2)

print("the numbers from A which are between 1 and 4 are :",A[idx_common])

(array([2, 3, 4], dtype=int64),)
(array([0, 1, 2, 3], dtype=int64),)
the numbers from A which are between 1 and 4 are : [2 3]


**4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
    url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
    iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])**

In [6]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url,delimiter =',',dtype = 'float',usecols = [0,1,2,3])

In [20]:
print(iris_2d.shape)
#m is the number of rows in iris_2d
#n is the number of columns in iris_2d

m = iris_2d.shape[0]
n = iris_2d.shape[1]

(150, 4)


In [17]:
#the first five elements in the dataset to know the element structure
iris_2d[:5,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [39]:
#finding the row indices where petallength (3rd column) > 1.5
idx1 = np.zeros([m,1])
idx1 = np.where(iris_2d[:,3] >1.5)

#finding the row indices where sepallength (1st column) < 5.0
idx2 = np.zeros([m,1])
idx2 = np.where(iris_2d[:,0] <5.0)

#finding the common indices
idx_common = np.intersect1d(idx1,idx2)
print("the row index/indices where that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0 is/are:",idx_common)

print("the row/s where that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0 is/are:",iris_2d[idx_common])

the row index/indices where that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0 is/are: [106]
the row/s where that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0 is/are: [[4.9 2.5 4.5 1.7]]


**PANDAS**

**1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).**

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [161]:
import pandas as pd
import numpy as np

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')


In [162]:
df.head(10)

Manufacturer       Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura     Integra    Small       12.9   15.9       18.8      25.0   
1          NaN      Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi          90  Compact       25.9   29.1       32.3      20.0   
3         Audi         100  Midsize        NaN   37.7       44.6      19.0   
4          BMW        535i  Midsize        NaN   30.0        NaN      22.0   
5        Buick     Century  Midsize       14.2   15.7       17.3      22.0   
6        Buick     LeSabre    Large       19.9   20.8        NaN      19.0   
7        Buick  Roadmaster    Large       22.6   23.7       24.9      16.0   
8        Buick     Riviera  Midsize       26.3   26.3       26.3      19.0   
9     Cadillac     DeVille    Large       33.0   34.7       36.3      16.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   
5         31.0         Driver only        NaN  ...        6.0   189.0   
6         28.0         Driver only      Front  ...        6.0   200.0   
7         25.0         Driver only       Rear  ...        6.0   216.0   
8         27.0         Driver only      Front  ...        5.0   198.0   
9         25.0         Driver only      Front  ...        6.0   206.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   
5      105.0   69.0         41.0           28.0          16.0     NaN   
6      111.0   74.0         42.0           30.5          17.0  3470.0   
7      116.0   78.0         45.0           30.5          21.0  4105.0   
8      108.0    NaN         41.0           26.5          14.0  3495.0   
9      114.0   73.0         43.0           35.0          18.0  3620.0   

    Origin              Make  
0  non-USA     Acura Integra  
1  non-USA      Acura Legend  
2  non-USA           Audi 90  
3  non-USA          Audi 100  
4  non-USA          BMW 535i  
5      USA     Buick Century  
6      USA     Buick LeSabre  
7      USA  Buick Roadmaster  
8      USA     Buick Riviera  
9      USA  Cadillac DeVille  

[10 rows x 27 columns]

In [163]:
df.shape

(93, 27)

In [164]:
df.info

<bound method DataFrame.info of    Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Pas

In [179]:
#creating new dataframe with columns Manufacurer to Type from original dataframe
cars_new = df.loc[:,"Manufacturer":"Type"]

#fitering the rows with 20 step size
cars_new[0:93:20]

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

**2. Replace missing values in Min.Price and Max.Price columns with their respective mean.**

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [180]:
#creating a new data frame cars from data frame
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
cars = df.loc[:,:]
column1 = df.columns[3]
column2 = df.columns[5]
cars2 = cars.rename(columns = {column1:'Min_price',column2:'Max_price'})

In [181]:
#finding the mean for min_price and max_price
cars2.head()
#print("the mean for Max_price is ",df.Max_price.mean())

Manufacturer    Model     Type  Min_price  Price  Max_price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

In [182]:
m1= cars2.Min_price.mean()
print(m1)

17.11860465116279


In [183]:
m2 = cars2.Max_price.mean()
print(m2)

21.459090909090918


In [184]:
cars2['Min_price'] = cars2['Min_price'].replace(np.nan,m1)
cars2['Max_price'] = cars2['Max_price'].replace(np.nan,m2)
#cars2['Max_price'].replace('Nan',m2,inplace = True)

cars2.head(10)

Manufacturer       Model     Type  Min_price  Price  Max_price  MPG.city  \
0        Acura     Integra    Small  12.900000   15.9  18.800000      25.0   
1          NaN      Legend  Midsize  29.200000   33.9  38.700000      18.0   
2         Audi          90  Compact  25.900000   29.1  32.300000      20.0   
3         Audi         100  Midsize  17.118605   37.7  44.600000      19.0   
4          BMW        535i  Midsize  17.118605   30.0  21.459091      22.0   
5        Buick     Century  Midsize  14.200000   15.7  17.300000      22.0   
6        Buick     LeSabre    Large  19.900000   20.8  21.459091      19.0   
7        Buick  Roadmaster    Large  22.600000   23.7  24.900000      16.0   
8        Buick     Riviera  Midsize  26.300000   26.3  26.300000      19.0   
9     Cadillac     DeVille    Large  33.000000   34.7  36.300000      16.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   
5         31.0         Driver only        NaN  ...        6.0   189.0   
6         28.0         Driver only      Front  ...        6.0   200.0   
7         25.0         Driver only       Rear  ...        6.0   216.0   
8         27.0         Driver only      Front  ...        5.0   198.0   
9         25.0         Driver only      Front  ...        6.0   206.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   
5      105.0   69.0         41.0           28.0          16.0     NaN   
6      111.0   74.0         42.0           30.5          17.0  3470.0   
7      116.0   78.0         45.0           30.5          21.0  4105.0   
8      108.0    NaN         41.0           26.5          14.0  3495.0   
9      114.0   73.0         43.0           35.0          18.0  3620.0   

    Origin              Make  
0  non-USA     Acura Integra  
1  non-USA      Acura Legend  
2  non-USA           Audi 90  
3  non-USA          Audi 100  
4  non-USA          BMW 535i  
5      USA     Buick Century  
6      USA     Buick LeSabre  
7      USA  Buick Roadmaster  
8      USA     Buick Riviera  
9      USA  Cadillac DeVille  

[10 rows x 27 columns]

**3. How to get the rows of a dataframe with row sum > 100?**

```
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
```

In [145]:
#creating a dataframe df
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [146]:
#knowing the shape of the dataframe
df.shape

(15, 4)

In [147]:
#printing the first 5 rows in the dataframe
df.head()

0   1   2   3
0  25  22  25  15
1  22  25  30  12
2  16  15  35  13
3  25  18  26  36
4  24  28  22  25

In [153]:
#lets create a new dataframe with sum of columns of original dataframe
df_new = df.agg("sum",axis ="columns")

df_new

0      87
1      89
2      79
3     105
4      99
5      85
6      91
7     124
8      89
9      84
10     76
11     85
12     94
13     83
14    113
dtype: int64

In [154]:
#finding the rows with sum>100

df_new[(df_new[:])>100]

3     105
7     124
14    113
dtype: int64

In [155]:
#finding the rows with sum>100 in the original dataframe
df[df.agg("sum",axis ="columns")>100]

0   1   2   3
3   25  18  26  36
7   38  31  36  19
14  33  34  22  24